# Generated by Django 3.2.8 on 2021-10-11 14:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('app', '0002_alter_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Barista',
        ),
    ]
