# Generated by Django 3.2.8 on 2021-10-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211013_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barista',
            old_name='description',
            new_name='mail',
        ),
    ]
